plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.14'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // JsonPath (for parsing Wikipedia JSON)
    implementation 'com.jayway.jsonpath:json-path:2.9.0'

    // Gson
    implementation 'com.google.code.gson:gson:2.10.1'
}

javafx {
    version = "21"
    modules = [ 'javafx.controls' ]
}

application {
    mainClass = 'edu.bsu.cs.GuiMain'
}

test {
    useJUnitPlatform()
}